-- V2: agent 加固
-- 1) knowledge_chunk.embedding 列冗余（向量实际存于 Spring AI pgvector 的 vector_store 表），删除
ALTER TABLE knowledge_chunk DROP COLUMN IF EXISTS embedding;

-- 2) 补货建议表（ReplenishmentScheduler 落库）
CREATE TABLE IF NOT EXISTS replenishment_suggestion (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku_code        VARCHAR(64)  NOT NULL,
    quantity        INTEGER      NOT NULL DEFAULT 0,
    safety_stock    INTEGER      NOT NULL DEFAULT 0,
    suggestion      TEXT,
    source          VARCHAR(16)  NOT NULL DEFAULT 'llm',
    created_at      TIMESTAMP    NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_replenishment_sku ON replenishment_suggestion(sku_code, created_at DESC);
